@startuml app-class-concept-uml

title Application Class Diagram - Conceptual View

actor User

usecase Login #LightCoral
usecase "Access Private Categories" as Categories #LightBlue
usecase "Access Private Products" as Products #LightGreen

User -> Login : Access Application
Login --> Categories : Success
Categories --> Products : Selects category

@enduml