@startuml mvc-seq-uml

skinparam roundcorner 20
skinparam responseMessageBelowArrow true

title Model View Controller

actor User as U
participant "View" as V  #LightBlue
participant "Controller" as C  #LightCoral
participant "Model" as M  #LightGreen
database DB as D

U -> C : Request
C -> M : Update
M -> D : Query
M <-- D : Response
C <-- M : Notify
C -> V : Update
U <-- V : Response

@enduml
