@startuml request-seq-uml

' left to right direction

header 

endheader

title Request Sequential Diagram

footer
<font color=red>Warning:</font> Do not use in production
endfooter


actor User

usecase Login
usecase "Access Private Categories" as Categories
usecase "Access Private Products" as Products

User -> Login : Access Application
Login --> Categories : Success
Categories --> Products : Selects category

@enduml
