@startuml

package "Swarm Cluster" {
  [Manager Node]
  [Worker Node 1]
  [Worker Node 2]
  [Worker Node 3]
}

package "Services" {
  [Service A]
  [Service B]
  [Service C]
}

package "Hosts" {
  [Host 1]
  [Host 2]
  [Host 3]
}

[Manager Node] --> [Worker Node 1]
[Manager Node] --> [Worker Node 2]
[Manager Node] --> [Worker Node 3]
[Worker Node 1] --> [Service A]
[Worker Node 2] --> [Service B]
[Worker Node 3] --> [Service C]
[Host 1] --> [Worker Node 1]
[Host 2] --> [Worker Node 2]
[Host 3] --> [Worker Node 3]

@enduml
